# 对话设置
conversation_setting:

  system: "现在你是一位金牌带货主播，你的名字叫{role_type}，你的说话方式是{character}。你能够根据产品信息讲解产品并且结合商品信息解答用户提出的疑问。"
  first_input: "我的{product_info}，你需要根据我给出的商品信息撰写一段直播带货口播文案。你需要放大商品的亮点价值，激发用户的购买欲。"


# 数据集生成设置
data_generation_setting:

  # 每个产品生成 ${each_product_gen} 个 conversion 数据，conversion 中包含【文案 + QA】，
  each_product_gen: 3

  # 每个 conversion 中的的对话数，文案为 1 个，其余会生成 ${each_conversation_qa} - 1 个 QA 
  each_conversation_qa: 5

  # 每个文案生成随机抽取 ${each_pick_hightlight} 个亮点
  each_pick_hightlight: 3

  # 每个文案生成后随机抽取 ${each_pick_hightlight} 个问题生成用户的提问
  each_pick_question: 3

  # 数据集生成 prompt
  dataset_gen_prompt: 现在你是一位金牌带货主播，你的名字叫{role_type}，你的说话方式是{character}。
                      我的{product_info}，你需要根据我给出的商品信息撰写一段至少600字的直播带货口播文案。你需要放大商品的亮点价值，激发用户的购买欲。
                      输出文案后，结合商品信息站在消费者的角度根据[{customer_question}]提出{each_conversation_qa}个问题并解答。
                      全部输出的信息使用我期望的 json 格式进行输出：{dataset_json_format}。注意 json 一定要合法。
 
  # 数据生成 json 格式
  dataset_json_format: 
    '{
      "conversation": [
        {
          "output": 直播带货口播文案，格式化一行输出，不要换行。
        },
        {
          "input": 消费者的问题,
          "output": 主播回答
        },
        {
          "input": 消费者的问题,
          "output": 主播回答
        },
        ... 直到问题结束
      ]
    }'

# 说明书生成设置
instruction_generation_setting:
  # 说明书生成 prompt
  dataset_gen_prompt: 我上传的是一个产品的详细说明，请帮我生成 markdwon 格式的说明书，需要包含产品名字、产品细节详情、卖点、亮点，越详细越好，只输出说明书即可。


# 角色及其性格
role_type:
  疆果慧伴: # 地域文化精通者
    - 热情友好
    - 耐心细致
    - 多语言交流能力 
    - 熟练使用各种网络热门梗造句
    - 熟悉新疆的特色产品
    - 称呼客户为[家人们]

# 商品信息结构体
product_info_struct:
  - 商品名是[{name}]，
  - 商品的亮点是[{highlights}]

# prompt: 购买东西时候，客户常会问题的问题，举例10个, 只列举大类就行
customer_question_type:
  - 价格与优惠政策
  - 产品质量
  - 产地与来源
  - 售后服务
  - 发货与配送
  - 用户评价与口碑
  - 包装与运输
  - 库存与补货
  - 支付方式
  - 营养成分与健康效益
  - 存储方式

# 第一个 prompt: 帮我列举10种常用的消费品种类，并每种举例5个其子类
# 每个类 prompt: 现在你精通任何产品，你可以帮我举例每个产品的6个亮点或特点，, 然后用python dict形式输出：{类名：[特点1, 特点2] ...} ，去掉特点12的字样，除python字典外的其他都不要输出，不要有任何的警告信息。 [xxx]
product_list:
  干果类:
    果肉类干果: 
      哈密大枣: [果实饱满,口感甜润,肉质细腻,干枣高达70%,维生素C含量高,含18种人体必需氨基酸及多种矿物质]
      杏干: [选用新疆优质鲜杏晾晒而成,保留了杏的自然风味,口感酸甜适中,肉质饱满有嚼劲,富含天然果糖,营养丰富]
      无花果干: [果肉饱满,甜度高,口感软糯,回味甘甜,富含多种维生素和矿物质,有助于改善便秘促进消化]
      葡萄干: [选用新疆优质葡萄晾晒而成,色泽晶莹剔透,口感香甜肉质饱满有嚼劲,营养丰富,种类繁多,便于保存和携带]
      椰枣: [果实大颗粒,口感丰富甜而不腻软糯适中,食用方法多样,益气补血,美容养颜,富含铁、钙、磷、维生素等多种营养成分]
      加州西梅干: [个大饱满,肉厚核小,果肉滑糯多汁,口感酸甜适中,天然健康,富含维生素C、维生素A和纤维素有助于增强免疫力和促进消化]
      桑葚干: [口感甘甜,颜色黑紫,形状饱满,富含蛋白质、脂肪、糖类、维生素和矿物质,抗氧化效果佳,补血清血,补肝护肾、补脑益智等多种健康功效]
      吊干杏: [耐存储,风味独特,甜中带酸,营养丰富,自然风干,稀有且珍贵的农产品]
      和田大枣: [颗粒饱满,果肉厚实,皮薄核小,营养丰富,口味甜醇,维生素C含量丰富]
      天山沙枣: [耐旱、耐盐碱、耐贫瘠、生命力极强,果实可食用,富含多种营养物质和活性物质,树皮、果实及叶子等均可入药,健脾止泻、清热凉血,花香四溢、可提取芳香油]
      天山乌梅: [果肉饱满,口感甜中带酸,富含有机酸、可转化为碱性物质、有益人体健康,具有促进胃酸分泌、调理胃肠、缓解便秘的功效,含有果酸等纤维物质、具有通便、抗衰老的作用]
      楼兰红枣(若羌红枣): [长圆形,表皮光滑洁净,维生素含量丰富,富含多种矿物质及微量元素,益气养血、安神,被国家绿色食品认证中心认定为绿色食品]
    坚果类干果:
      阿克苏纸皮核桃: [壳薄如纸,果大肉厚,口感酥脆,富含多种维生素和矿物质,拥有得天独厚的生长环境,中国国家地理标志产品]
      喀什巴旦木: [新疆喀什地区名贵特产,营养价值高,含油量、含糖量高,富含植物油、蛋白质、淀粉、糖以及多种维生素和矿物质,明目、增强身体抵抗力等健身滋补功效,可用于治疗高血压、神经衰弱等多种疾病]
      腰果: [属于优质的蛋白质来源,抗氧化、促进皮肤健康、维护神经系统健康,有助于维持身体的正常生理功能,适应性强,喜温、耐干旱贫瘠,具有一定的抗风能力]
      杏仁: [甜杏仁可食用,苦杏仁一般入药,富含蛋白质、脂肪、糖类、胡萝卜素、B族维生素、维生素C、维生素P以及钙、磷、铁等营养成分,良好的抗氧化性和稳定性,具有滋润保湿、美白淡斑的作用,其含有的苦杏仁苷能抑制癌细胞生长和增殖]
      碧根果: ["营养丰富，富含蛋白质和脂肪",口感香脆,味道甜美, "富含抗氧化物质，有益健康","形状美观，适合作为零食或礼品","有助于改善记忆力，促进大脑健康","适合多种烹饪方式，如烘焙、炒食等"]
      鲍鱼果: [喜欢高温高湿的气候和深厚而排水良好的土壤,营养价值极高,被誉为“坚果之王”,富含优质蛋白质对身体健康有多种益处,口感香脆、味道醇厚、有淡淡的甜味和奶香、热量较高]
      夏威夷果: [果仁营养丰富,口感香酥滑嫩,有独特的奶油香味,干果皇后,世界坚果之王,具有调节血脂、益智、软化血管、降低心脏病和高血压发病率的作用] 
      奇亚籽: [富含Omega-3脂肪酸,含有多种抗氧化剂如维生素E、维生素C等,控制血糖、促进排便、轻身减肥的功效,调节胆固醇、促进心脏健康、美肤养颜和延缓衰老,吸水能力强]
    其他干果类农产品:
      枸杞: [枝条细弱、叶片呈卵形、果实为卵状浆果红色,具有滋补肝肾、益精明目的功效,含有丰富的营养成分,具有多种药理作用：如免疫促进作用、造血功能促进作用、抗衰老作用、抗突变作用、抗肿瘤作用等,是中华民俗文化八大吉祥植物之一,耐盐碱]
      鹰嘴豆: ["属于豆科鹰嘴豆属草本植物，因其形状如鹰嘴而得名","富含蛋白质、膳食纤维、维生素B群和多种矿物质,营养价值高","有助于降低胆固醇、控制血糖，适合糖尿病患者食用","富含异黄酮，对女性健康有益，可缓解更年期症状","适应性强，耐旱、耐盐碱，适合在新疆等干旱地区种植","烹饪方式多样，可煮、炒、烤、磨成粉制作各种美食"  ]  
      奶疙瘩: ["源自新疆等牧区，是哈萨克、柯尔克孜等草原游牧民族的传统食品","分干湿两大类，传统奶疙瘩是咸酸的，现代还有甜酸味的创新口味","富含优质蛋白质、钙、镁、锌等营养元素，易于人体吸收","制作工艺天然，富含益生菌，有利于维持肠道健康","食用方式多样，可直接食用，也可搭配奶茶、作为面条调味品等","便于携带和保存，是牧区人民放牧、远行时的理想干粮"]
      新疆奶酪: ["源自中国新疆，是蒙古族、哈萨克族等游牧民族的传统食品","制作工艺独特，通过自然发酵和凝乳工艺制成，不添加防腐剂","营养丰富，含有高浓度的蛋白质、钙、磷等营养成分，被誉为“奶黄金”","口感多样，有软嫩爽滑的新鲜奶酪，也有风干后硬实有嚼劲的奶疙瘩","风味醇厚，奶香浓郁，是新疆地区广受欢迎的特色美食","适合各年龄段人群食用，儿童食用可预防龋齿，成人食用可补充身体所需微量元素"]
  瓜果:
    瓜果类:
      哈密瓜: ["新疆维吾尔自治区哈密地区特产，中国国家地理标志产品","形态各异，风味独特，瓜肉肥厚，清脆爽口，含有多种糖分和纤维素","营养价值高，含有丰富的水分、碳水化合物、膳食纤维、维生素和矿物质","性喜充足的阳光和较大的昼夜温差，主要产于新疆哈密、吐鲁番、鄯善等地","品种多达100多个,形状、大小、色泽、风味各异，名贵的品种有五十多个","食用方式多样，可直接食用，也可制作成果汁、果酱、甜品等"]
      吐鲁番葡萄: ["产地优越，位于新疆吐鲁番地区，特殊的地理位置和气候使得葡萄品质上乘","品种繁多,按颜色分为红葡萄、紫葡萄、白葡萄、黑葡萄和绿葡萄等200多个品种","成熟时间跨度大,早熟品种6月末到7月初成熟,晚熟品种可至10月份成熟","营养丰富，含有蛋白质、矿物质、维生素及多种氨基酸等营养物质","口感极佳，果穗大、果粒饱满、色泽鲜艳、皮薄肉嫩、果汁多而浓","产业发达，是吐鲁番市发展经济的一项特色支柱产业，远销全国各地及海外市场"]
      库尔勒香梨: ["新疆维吾尔自治区特产，中国国家地理标志产品，产自库尔勒市、阿克苏市等地","果实广卵圆形或纺锤形，成熟时果皮绿色或黄绿色，部分果实带有红晕，果皮较薄","果肉白色，细嫩酥脆，汁多味甜，有芳香，近果心处略酸，香味浓郁","耐贮藏，营养丰富，含糖、氨基酸、维生素及各种碳水化合物，有“梨中珍品”之称","具有“润肺、凉心、消痰、消炎、止咳、解疮毒酒毒”等医疗作用，是食疗佳品","得天独厚的自然地理和气候条件决定了库尔勒香梨的独特品质，是当地重要的经济作物"]
      阿克苏苹果: ["主要产地位于新疆阿克苏地区温宿县，天山南麓塔里木盆地地北缘，地理环境独特","果形扁平，果面光滑细腻、色泽光亮自然，果核部分糖分堆积成透明状，形成独特的“冰糖心”","口感甜脆爽口、果肉细腻、皮薄少渣、汁多味美，含糖量高，甜度远超普通苹果","生长环境优越，昼夜温差大、光照充足，用无污染的冰川雪融河流浇灌、沙性土壤栽培","富含维生素C等多种营养成分,具有心血管保护、延缓记忆衰退、美容养颜等多种健康功效","采摘时间严格控制在每年10月25日之后,较长的生长期让阿克苏苹果更多汲取大自然的天地精华"]
      库车小白杏: ["果肉厚、纤维少、汁液多、甜味浓","果实中富含维生素、无机盐等多种营养物质","具有润肺化痰、清热解毒的功效","果皮光滑无毛，洗后即可食用","含糖量高、含酸低，风味浓郁","被誉为“树上蜂蜜”，营养价值高"]
      八角梨: ["新疆特产水果，外形独特，有不规则凸起，形状并不规则","果肉细腻柔软，口感香甜，甜里透出一股果味清香","果核可食用，增加了食用的趣味性和营养价值","富含多种营养物质，如维生素、膳食纤维、果糖等","具有促进新陈代谢和血液循环的功效，对孕妇和小孩有益","适应性强，在新疆地区四季均可食用，是当地人喜爱的水果之一"]
      榅桲: ["属于蔷薇科榅桲属落叶小乔木或灌木，果实梨形黄色有香味","原产于中亚，中国新疆喀什莎车和田等地有栽培，陕西江西福建等地也有引种","果实可入药，具有祛湿解暑舒筋活络功效，主治伤暑呕吐腹泻消化不良等症状","含丰富营养物质,如糖分鞣质原果胶有机酸和维生素C等","种子含粘质达20%，可用于纺织工业，枝条耐修剪，适宜作绿篱","喜温暖有庇护厚实肥沃排水顺畅弱酸性土壤，繁殖方法有播种分株扦插等"]
      喀什无花果: ["是我国稀有果品之一，品质优良，誉满全疆","果实甘甜可口,含糖量高达24%至74%以上","富含多种维生素，食用药用价值高","果形扁圆,单果重量可达100至200克","可鲜食，也可制成果干、果酱等","主要产于喀什市浩汗乡、伯乡及阿图什等地"]  
      叶城石榴: ["产自新疆叶城县，该地素有‘石榴之乡’美誉","果皮鲜红耀眼，籽白里透红，籽粒大，味甜多汁","含糖量高达19%左右,维生素每百克含11毫克","分甜石榴和酸石榴两大类，甜石榴口感甘甜，酸石榴味酸甜带香","得益于昆仑山北麓独特气候，霜期短、日照时间长、昼夜温差大","近年来种植面积不断扩大，已成为当地农民增收致富的重要产业"]  
      新疆西瓜: ["产地分布广泛，主要产地包括昌吉、吐鲁番、石河子、博尔塔拉蒙古自治州等地","口感甜度高、脆爽多汁，得益于新疆独特的昼夜温差大、日照时间长的气候条件","外观多为绿色或青绿色外皮，有明显的条纹或网纹，形状多为椭圆形或圆形","品种多样,如吐鲁番的“金城5号”“甜王”西瓜,下野地西瓜,巴州尉犁西瓜等","富含葡萄糖、果糖、蔗糖等多种营养物质，具有消烦止渴、解暑热等功效","是新疆特色农产品之一，种植面积广泛，市场需求量大，远销国内外多个地区"]  
      马奶子葡萄: ["又名马乳葡萄，因其果实形状如马奶子头而得名，主产于新疆吐鲁番盆地和南疆的墨玉、皮山县等地","果穗圆柱形,歧肩大且有分枝,果粒圆柱状,平均粒重6克,最大可达8克,白绿色，甘甜多汁，质脆爽口，有小核，宜鲜食","含有丰富的营养成分,包括葡萄糖、维生素A、维生素B2(核黄素)、烟酸(烟酰胺)、钾、铁、铜等矿物质,以及膳食纤维和抗氧化物质","具有多种健康功效，如快速补充能量、阻止血栓形成、降低血清胆固醇、抗衰老、清除体内自由基、抗癌等","栽培历史悠久,据《册府元龟》记载,唐太宗破高昌国(今吐鲁番)得马乳葡萄和葡萄酒酿造技术,说明在吐鲁番栽培葡萄的历史在1300年以上","适合肾炎、高血压、水肿患者，儿童、孕妇、贫血患者，神经衰弱、过度疲劳者，肺虚咳嗽、盗汗者，风湿性关节炎患者等食用，但糖尿病患者应适量食用"]  
      喀什甜杏: ["产于新疆喀什地区，享有得天独厚的地理和气候条件","果实大、果肉厚、汁多味甜，口感极佳","富含多种维生素和矿物质，营养价值高","成熟时间通常在6月至8月间,是夏季的时令水果","广泛用于制作杏干、杏酱等加工品，深受消费者喜爱","喀什甜杏产业带动了当地经济发展，增加了农民收入"]
      博乐红提: ["产自新疆博乐市，品种优良，果实品质上乘","果穗紧凑，果粒大而均匀，色泽鲜艳，呈紫红色或红黑色","果皮薄而韧，果肉脆嫩多汁，甜度高，口感极佳","富含葡萄糖、果糖、维生素及多种矿物质，营养价值丰富","耐贮运，货架期长，适合远销国内外市场","博乐红提已成为当地的重要经济作物，推动了农业产业的发展"]
      轮台小白杏: ["产于新疆维吾尔自治区轮台县，中国国家地理标志产品","果肉黄白色，肉质细嫩，味极甘甜，多汁，品质上乘","平均单果重19.7克，果形、核形端正，可溶性固形物含量高","含有氨基酸、维生素、糖分等多种对人类有益的元素","杏仁含植物油、蛋白质、淀粉及多种微量元素，营养价值高","6月中下旬成熟,宜鲜食又宜加工取仁,用途广泛"]  
      巴旦杏: ["主要产于新疆天山以南喀什绿洲的多个县，是维吾尔族珍视的干果","非杏类，而是桃属中扁桃亚属的植物，果肉干涩无汁，主要食用果仁","果仁味甜香，含有脂肪、蛋白质、淀粉、糖及多种微量元素","可用于制作罐头、高级糕点和糖果，也可做营养滋补品","具有医药用途，可用于治疗高血压、神经衰弱等疾病","在国际市场干果交易中占重要地位，售价高"]
      喀拉布拉桃子: ["新疆维吾尔自治区伊犁哈萨克自治州新源县特产，全国农产品地理标志","果实较大,平均单果重260克,最大可达650克","果肉黄色，硬溶质，多汁，风味浓甜，有微香","产区气候适宜桃树生长，光照充足，热量丰富","富含多种营养物质，口感极佳，深受消费者喜爱","对当地农业发展有重要推动作用"] 
      沙棘果: ["是世界上含有天然维生素种类最多的珍贵经济林树种之一","维生素C含量远高于鲜枣和猕猴桃,被誉为天然维生素的宝库","具有治疗烧伤、放射病、心脏病、青光眼等疾病的药用价值","适应性强，能在多种土壤类型和气候条件下生长","通常3年生开始结果,5年生时进入盛果期,单株产果量可达数千克","是一种落叶灌木或小乔木，果实为圆球形，颜色橙黄或桔红"]
      白桑葚: ["唯一没有酸味的果桑品种，口感蜜甜","营养含量相较于黑色桑葚略少，一般不用于制酒","作为水果食用极佳，但相比而言更推荐黑桑葚","因白桑葚相较于其他桑葚品种特色不突出，主要以其无酸味的甜度著称","是一种果桑的果实，外观通常为白色或淡黄色","富含多种维生素，对人体健康有益"]
      尉犁甜瓜: ["新疆维吾尔自治区巴音郭楞蒙古自治州尉犁县特产，全国农产品地理标志","外形呈卵圆形或圆形，香气十足，皮薄肉厚，细脆爽口","土壤盐碱成分含量高有利于其生长发育，并能提早成熟期","果肉橘红，含糖量高，品质佳，口感独特","尉犁县地区昼夜温差大，有利于甜瓜的光合作用和糖分积累","是当地重要的经济作物，对农民增收有积极作用"]  
      阜康蟠桃: ["新疆阜康市特产，个头大、均匀，色泽红中泛绿，绿中透红","果肉呈奶白色，肉质细腻、甘甜可口、皮韧易剥、入口即化","富含维生素B及多种微量元素,营养价值高","具有补心活血、清热养颜、润肠通便、帮助消化的功效","主要栽种品种有瑶池早红、早露蟠等，品质优良，丰产易栽培","产地气候属中温带大陆性干旱气候，光照充足，昼夜温差大，为蟠桃生长提供了理想环境"] 
      西梅: ["含有丰富的维生素A及纤维素,同时兼含铁和钾等矿物质,不含脂肪和胆固醇","具有保护视力、开胃消食、润肠通便、美容养颜等功效","果实呈紫色,8月中旬成熟,适合一般人群食用,但腹泻、消化性溃疡者不宜食用","含有抗氧化成分,能保持皮肤水分，并延缓皮肤老化","是蔷薇科植物,可用保鲜膜包裹后冷藏保存","我国的西梅多为美国进口,购买时需仔细挑选,避免选择有损伤的西梅"] 
      黑加仑: ["学名黑穗醋栗，又名黑醋栗、黑豆果、紫梅，为多年生小灌木","果实富含维生素C、花青素、磷、镁、钾、钙等营养成分","具有预防痛风、贫血、水肿、关节炎等多种保健功效","果实为黑色小浆果,内富含维生素C和多种矿物质,可食用也可加工成果汁、果酱等食品","主要分布于新疆北部的戈壁滩盆地，常年依靠雪水生长","栽培时需选择平坦肥沃的地块，注意灌水条件和人工管理"]
      猫屎瓜: ["又名猫儿屎、鬼指头、猫屎筒，为木通科猫屎瓜属落叶灌木植物","果实呈蓝紫色，多浆汁，形状似猫屎，因此得名","果肉富含糖类、蛋白质、脂肪、果胶、维生素和矿物营养，味甜如蜜","可供鲜食和加工制糖、酿酒、食品、果胶、果冻、果酱等","分布于秦岭、巴山的深山之中，在四川、重庆、湖北等地山区有分布","其种子含油量为18%~22%，油可食用，还可制肥皂，做工业用油"]
  优质禽畜类:
    优质禽畜类:
      阿勒泰羊: ["历史悠久,有1200年以上的饲养历史,唐代时曾作为贡品进献宫廷","体型巨大，四肢刚劲有力，肌肉发达，能长途跋涉","体内脂肪含量高，能在严寒和酷暑中保持机体代谢平衡，抗病力强","肉质鲜嫩可口、无膻味，具有滋补药用作用，是绿色食品","肉脂生产性能高，羔羊生长发育快且早熟突出","适应能力强，能在恶劣的自然环境中生存并保持优良的生产性能"]
      伊犁马: ["体格较大，是中国体格较大的优良马种之一","外貌俊秀，体格魁伟，抗病力强，耐粗放，适应性强","善驰骋，速度快，耐持久力强，运步轻快","具有乘挽兼优的生产性能，既可用于农业耕作、短途运输，也可用于军用","还具有良好的产肉、产奶性能","力速兼备，挽乘皆宜，长途骑乘擅长走对侧步"]
      新疆褐牛: ["耐寒性强，能在严寒的冬季正常生活和繁殖","抗病能力强，能够抵抗多种疾病，降低养殖风险","肉质优良，鲜美滑嫩，蛋白质含量高，脂肪含量适中","牛奶营养价值高，干物质含量比普通牛奶高，奶香味浓郁","适应性强，对饲料的适应性较强，能够充分利用当地丰富的草料资源","生态环境友好，放牧型牛种，对环境的破坏较小"]
      和田羊: ["适应荒漠生态环境，抗逆性强，耐干旱炎热","耐粗饲，抗病力强，易于饲养管理","羊毛是编制地毯和提花毛毯的优质原料","羊肉具有低脂肪、高蛋白、低胆固醇等特点","体型较小但体格结实，四肢健壮，行动敏捷","产区在和田地区昆仑山区，全疆存栏量大，是新疆地区的重要畜禽品种"]  
      巴音布鲁克黑头羊: ["头部毛色为黑色","体躯被毛白色","肉质细嫩","味道鲜美","无膻味",细嫩多汁]
      柯坪羊肉: ["鲜嫩的口感", "独特的香气", "新疆羊肉中的佼佼者", "肉质优良", "口感独特", "膻味小"]  
      塔城巴什拜羊: ["品质优良", "口感独特", "肉质细嫩多汁", "膻味极小", "繁殖率高", "早熟性理想品种"]  
      哈密瓜羊: ["哈密地区特有", "肉质鲜美", "带有哈密瓜清香", "自然环境下生长", "口感独特", "羊种优良"]  
      多浪羊: ["肉脂兼用型品种", "体大产肉多", "肉质鲜嫩", "被毛含绒毛多", "繁殖率高", "早熟性理想"]  
      尉犁罗布羊: ["尉犁县主体优势畜种", "遗传基因稳定", "抗病能力强", "精肉多脂肪少", "无膻味", "肉质口感好"] 
      木垒羊肉: ["无膻味", "肉质鲜嫩", "昌吉回族自治州特产", "口感独特", "营养丰富", "品质优良"]  
      尼雅羊: ["荒漠生态环境适应性强", "肉质鲜美", "生产优质地毯毛", "低脂肪高蛋白", "烤制品肉香味独特", "胆固醇低"]  
      和田黑鸡: ["体型小行动敏捷", "肉质瘦肉健", "鲜嫩细腻鲜美味香", "主要分布于和田地区", "觅食力强", "善飞"] 
      拜城油鸡: ["体态肥美骨细肉多", "肉质细嫩香味浓郁", "味道鲜美抗病力强", "产于拜城县", "饲料报酬高", "生长快存活率高"] 
      阿克陶斗鸡: ["体大健壮善斗", "生长快存活率高", "饲料报酬高抗病力强", "主要分布于阿克陶县", "体型健壮", "善斗性强"] 
      天山草鸡: ["饲养于天山北坡", "饮天山雪水吃野生虫草", "营养价值高", "具备滋补功能", "产于昌吉州", "半牧半饲方式"] 
      于田麻鸭: ["蛋肉兼用型品种", "抗逆性强适应力强", "易饲养管理", "产蛋量高抗病力强", "成活率高", "主要分布于于田县"]  
      喀什土鸡: ["肉质紧实有嚼劲", "口感鲜美", "产于喀什地区", "肉质优良", "风味独特", "饲养环境独特"] 
      和田黑鸭: ["黑色羽毛独特", "口感细嫩多汁", "风味独特", "产于和田地区", "肉质优良", "饲养环境独特"]  
      吐鲁番斗鸡: ["体型高大健壮", "羽毛紧密脚爪强健", "肉质鲜美富有营养", "产于吐鲁番地区", "善斗性强", "生长健壮"] 
      塔里木鸽: ["体型适中", "肉质细嫩", "口感鲜美", "产于塔里木盆地", "饲养环境独特", "风味独特"] 
      新疆驼奶: ["富含多种营养成分", "如维生素C、不饱和脂肪酸", "具有极高营养价值", "新疆各地均有分布", "营养丰富全面", "口感醇厚"] 
      新疆牛肉干: ["选用优质牛肉", "传统工艺加工", "口感鲜美紧实有嚼劲", "广泛分布于新疆", "肉质优良", "营养丰富"]
      胡杨鸡: ["具有独特生长环境", "饲养方式独特", "肉质鲜美", "富含营养", "产于喀什等地", "风味独特"]  
  粮食作物类:
    粮食作物类:
      小麦: ["品质优良", "适合在温带大陆性气候、光照充足的环境下生长", "耐旱性强", "是全球重要的粮食作物之一", "富含膳食纤维和矿物质", "可用于制作面粉、面包等多种食品"]  
      高粱: ["适应性强", "可用作饲料、酿酒原料等", "耐旱耐盐碱", "在贫瘠土地上也能生长", "富含糖分和淀粉", "是传统的酿造原料"]  
      棉花: ["品质优良、产量高", "充足的阳光、较大的昼夜温差为生长提供了良好环境", "纤维柔软细长", "是纺织工业的重要原料", "种植广泛", "具有经济价值和社会价值"]  
      甜菜: ["种植面积广，产量高", "甜菜制品如糖、甜菜碱等需求大", "富含糖分", "是重要的糖料作物", "适应性强", "能在多种土壤类型中生长"]  
      水稻: ["品质优良", "在绿洲和灌溉条件较好的地区有种植", "是重要的粮食作物之一", "富含碳水化合物和多种维生素", "能适应不同的生长环境", "具有高产潜力"] 
      谷子: ["种植历史悠久", "营养价值高，含有丰富的蛋白质和多种维生素", "耐旱性强", "适应性强", "是重要的杂粮作物", "是北方地区的主要粮食作物之一"] 
      藜麦: ["高蛋白、低脂肪", "被誉为“营养黄金”", "富含多种氨基酸", "适应性强，能在多种环境中生长", "是素食者和健身人士的理想食品", "有助于降低胆固醇"]  
      鹰嘴豆: ["种植历史悠久", "富含蛋白质、脂肪和多种维生素，有药用价值", "耐旱性强", "能在贫瘠土壤中生长", "是中东和地中海地区的重要食品", "有助于控制血糖"]  
      青稞: ["耐寒、耐旱", "适合在高寒地区种植，营养价值高", "富含膳食纤维和β-葡聚糖", "有助于降低胆固醇", "是藏族人民的主要粮食作物", "是高原地区的特色食品"]
      黄豆: ["种植面积广泛", "富含蛋白质和脂肪", "是重要的植物蛋白来源", "能制作多种豆制品", "富含不饱和脂肪酸", "有助于预防心血管疾病"] 
      豌豆: ["新疆常见的豆类作物", "富含膳食纤维和维生素", "适应性强", "能在多种土壤中生长", "有助于降低血糖", "是蔬菜中的重要一员"]  
      荞麦: ["高原地区的重要粮食作物", "富含矿物质和维生素", "有助于降低血压", "是糖尿病患者的理想食品", "适应性强，能在寒冷和贫瘠的环境中生长", "是传统的健康食品"] 
      胡麻: ["重要的油料作物", "含有可溶性植物纤维素，可以降低胆固醇", "富含亚麻酸和亚油酸", "有助于预防心血管疾病", "适应性强，能在多种环境中生长", "是传统的食用油和药用植物"] 
      向日葵: ["种植历史悠久，产量高，品质好", "籽可以榨取向日葵油，富含不饱和脂肪酸", "富含维生素E", "有助于抗氧化", "适应性强，能在多种环境中生长", "是观赏和食用兼具的植物"] 
      红花: ["具有药用和食用价值", "籽可以榨油，花瓣可用于制作红花茶、红花酒", "富含红色素", "可用于食品着色和制药", "有助于活血通经", "是传统中药材之一"] 
      枸杞: ["种植规模逐渐扩大，品质优良", "富含多种营养成分，如维生素、矿物质和氨基酸", "具有抗氧化作用", "有助于增强免疫力", "适应性强，能在多种环境中生长", "是传统中药材和保健食品"]  
  民族工艺品:
    民族工艺品:
      玉雕: ["和田玉质地细腻，纯洁混白", "镌刻的玉雕作品栩栩如生", "远销海外多个国家和地区", "展现了中国传统工艺的精湛", "具有收藏和投资价值", "承载了丰富的文化内涵"]  
      英吉沙小刀: ["造型精美，纹饰秀丽", "刃口锋利，实用性强", "少数民族男性喜欢的随身饰品", "家庭中不可缺少的生活用具", "体现了民族工艺的独特魅力", "具有传承和纪念意义"]  
      喀什土陶: ["具有观赏和使用双重价值", "分为素陶、釉陶和彩绘釉陶三种", "展现了古代陶瓷文化的魅力", "是新疆地区特有的工艺品", "制作工艺独特，历史悠久", "图案多样，富有民族特色"]  
      吐鲁番陶器: ["制作工艺精湛，雕刻技艺独特", "图案设计丰富，融合了多元文化", "体现了古代丝绸之路的文化交流", "是新疆地区的重要文化遗产", "作品精美，具有收藏价值", "常用于家居装饰和礼品赠送"]  
      艾德莱斯绸: ["色彩绚丽、鲜艳，图案细腻严谨", "质地柔软，轻盈飘逸", "是新疆姑娘出嫁的首选礼服", "体现了新疆地区独特的纺织技艺", "常用于制作民族服饰和装饰品", "具有浓郁的地域和民族特色"]  
      哈萨克族毡毯: ["采用哈萨克族民间传统技艺制作", "花毡绣制工艺复杂，图案繁多", "美观大方，实用性强", "是哈萨克族文化的重要组成部分", "常用于家居装饰和保暖", "具有传承和弘扬民族文化的意义"] 
      哈萨克族羊皮编织品: ["以精美的图案和精湛的技艺著称", "是游牧民族的重要生活用品", "体现了哈萨克族人民的智慧和创造力", "常用于制作衣物、家居用品等", "具有保暖和装饰双重功能", "是民族文化的瑰宝"] 
      维吾尔族草编技艺: ["采用天然材料编织成各种实用器物", "如篮子、帽子等，实用性强", "体现了维吾尔族人民的勤劳和智慧", "是新疆地区特有的民间工艺", "作品精美，具有装饰价值", "常用于家居装饰和礼品赠送"]  
      铜器: ["制作技艺历史悠久", "以壶、碗、瓶、罐为代表，制作精美", "体现了中国古代金属工艺的精湛", "常用于家居装饰和日常生活", "具有收藏和投资价值", "是民族文化的重要组成部分"] 
      木雕: ["以当地特有的木材为原料", "雕刻技艺精湛，作品题材广泛", "体现了中国传统木雕艺术的魅力", "常用于家居装饰和艺术品收藏", "具有独特的艺术价值和审美价值", "是民族文化的瑰宝"] 
      桑皮纸: ["采用桑树皮为原料制作", "质地坚韧，色泽古朴", "常用于书法、绘画和包装", "体现了中国古代造纸技术的精湛", "具有环保和可持续的特点", "是民族文化的传承和弘扬"]  
      模戳印花布: ["特有的印花布织染技艺", "采用天然植物制成的颜料印制", "图案不褪色，色彩鲜艳", "体现了新疆地区独特的纺织和印染技艺", "常用于制作民族服饰和家居用品", "具有浓郁的地域和民族特色"]  
  民族乐器: 
    维吾尔族乐器:
      喀什热瓦普: [全长1.3米,声音清脆悦耳,常用于独奏,常用于合奏,作为演唱“十二木卡姆”的伴奏乐器",伴奏乐器]  
      达甫: [也称手鼓,是维吾尔等民族用手击奏的打击乐器,规格有大规格,规格有中规格,规格有小规格,是维吾尔族乐队中的“灵魂”]
      艾捷克: ["又名哈尔扎克，起源于古代的波斯", "主要用于演奏民间歌曲和木卡姆曲调",历史悠久,形制独特,演奏多样,民族特色]
      胡西它尔: ["维吾尔族的民间拉弦乐器",维吾尔族拉弦,风格独特,技艺灵活,传统乐器,悠扬柔美]
    哈萨克族乐器: 
      冬不拉: ["身长约1米,音箱由整块木料凿成", "最普及的一种拨弦乐器",音域宽广,轻便易携,制作精美,种类繁多]
      库布孜: ["哈萨克族流传的弹拨乐器",音色独特,技艺复杂,非遗文化,制作精良,旋律美妙]
      色布孜克: ["哈萨克族的吹奏乐器",类似竖萧,制作多样,小巧便携,音色柔和,双声部]
      阿萨塔亚克: ["哈萨克族的拉弦乐器",摇撼发声,装饰精美,文化象征,独特音色,神秘氛围]
    蒙古族乐器:
      托布秀尔: ["传统弹拨乐器，音箱呈椭圆形", "音色柔和，富有草原风情",制作简便,演奏多样,材质多样,文化象征]
    锡伯族乐器: 
      东布尔: ["形状类似汉族的三弦，音箱为椭圆形", "音色浑厚，常用于锡伯族的民间音乐演奏",音色圆润,制作精良,流传广泛,文化象征]
    俄罗斯族乐器: 
      巴扬: [俄罗斯族的传统手风琴","具有独特的音色和表现力","在新疆俄罗斯族聚居区常见","民间乐器之一","音色丰富多变","表现力强大"]
    塔吉克族乐器: 
      热布卜: [弹拨乐器","音箱圆形或椭圆形","用薄木板制作，正面蒙皮","音色清脆悦耳","常用于独奏或伴奏","民族特色鲜明"]
    其他民族乐器: 
      鹰笛: [由鹰翅膀骨制作","有藏族和塔吉克族两种","常用于独奏","塔吉克族鹰笛是古老乐器","流行于新疆多地","具有边棱气鸣特色"]  
      考木孜: ["柯尔克孜族弹拨乐器","木制音箱", "有3根弦","自弹自唱","演奏技巧多样","民族传统乐器"]
      纳格纳鼓: ["维吾尔、塔吉克、乌孜别克等民族使用","打击乐器","常用于歌舞伴奏","节奏明快","增强舞蹈气氛","传统乐器之一"]
      斯不兹厄: ["哈萨克族吹奏乐器","传统乐器","音色独特","常用于民族音乐","具有民族特色","演奏技巧丰富"]
      巴拉曼: ["维吾尔族吹奏乐器","音色悠扬","常用于独奏或合奏","民族传统音乐中常见","具有浓厚民族风味","制作精美"]
      布尔格 : ["哈萨克族打击乐器","传统乐器","节奏鲜明","常用于舞蹈伴奏","增强音乐节奏感", "具有民族特色"]
      冬巴鼓: ["哈萨克族传统乐器", "常用于民族音乐","音色浑厚","演奏技巧独特","具有民族历史意义","文化传承的象征"]
      新疆唢呐: ["维吾尔语称苏尔奈","源于西亚波斯和阿拉伯","音色高亢激昂","常用于民间节庆","婚礼等场合演奏","传统乐器代表"]
      沙巴依: ["维吾尔、乌孜别克等民族使用","摇奏类体鸣乐器","器形独特","铁环碰击木棍发声","常用于歌舞伴奏","节奏明快富有感染力"]
  中草药类:
    中草药类: 
      薄荷: [疏散风热,有助于缓解感冒、咳嗽等症状,清利头目,提神醒脑,缓解头痛、眩晕等问题,"利咽透疹，对于咽喉肿痛、麻疹不透等症状有一定的疗效"]
      枸杞: [富含花青素,具有强大的抗氧化能力,有助于延缓衰老,"滋补肝肾，能够改善肝肾功能，增强体质","明目护眼，对眼睛有一定的保护作用，可以缓解视疲劳","新疆吐鲁番、阜康等地是黑枸杞的重要产区"]
      大黄: [泻热通便,有助于缓解便秘等症状,有助于缓解腹胀等症状,破积行瘀,能够消散淤血,改善血液循环]  
      锁阳: ["补肾壮阳", "益精养血", "润肠通便", "增强体质", "改善循环", "温阳固本"]  
      雪莲: ["散寒除湿", "调经止血", "补肾强身", "抗衰老力", "活性物质", "珍稀药材"]  
      薰衣草: ["镇定安神", "助眠放松", "祛斑美容", "清热解毒", "舒缓情绪", "芳香怡人"] 
      薄荷: ["疏散风热", "提神醒脑", "利咽透疹", "清凉舒爽", "清新口气", "缓解头痛"] 
      贝母: ["清肺化痰", "止咳平喘", "润肺养喉", "药效温和", "适用广泛", "传统药材"]  
      黄芪: ["补气升阳","固表止汗","利水消肿","生津养血","行滞通痹","托毒排脓"]
      肉苁蓉: ["滋补精血", "养肝护肝", "润肠通便", "增强体质", "温补肾阳", "沙漠人参"]  
      甘草: ["补脾益气", "清热解毒", "祛痰止咳", "调和药性", "缓急止痛", "药中之国老"] 
      板蓝根: ["清热解毒", "凉血利咽", "抗病毒强", "增强免疫", "治疗感冒", "药用广泛"]  
      菊苣: ["清热解毒", "利尿消肿", "调节血脂", "改善消化", "营养丰富", "天然草本"] 
      阿魏: ["消积","散痞","杀虫",蒜样臭气,药用广泛,挥发油高]
      秦艽: ["祛风湿","舒筋络","清虚热",止痹痛,质硬而脆,断面油性] 
      麻黄: ["发汗散寒","宣肺平喘","利水消肿",辛散作用,柔软易断,断面黄白]
      大力子: ["疏散风热","宣肺透疹","解毒利咽",果硬油富,味苦后辛,利咽通便]
      党参: ["补中益气，增强体质", "健脾益肺，改善呼吸", "养血生津，滋润身体", "提高免疫力", "促进消化", "抗疲劳，增加活力"]
      芍药: ["养血调经，平衡内分泌", "敛阴止汗，调节体温", "柔肝止痛，缓解不适", "平抑肝阳，稳定情绪", "美容养颜，改善肤质", "促进血液循环"] 
      益母草: ["活血调经，改善女性健康", "利尿消肿，排出多余水分", "清热解毒，抗炎抗菌", "调节免疫功能", "缓解痛经，舒缓不适", "促进子宫收缩，帮助恢复"]  
      罗布麻: ["清火护肝，保护肝脏健康", "降脂降压，维护心血管", "消食化滞，促进消化", "利尿消肿，减轻水肿", "调节血糖，稳定代谢", "抗氧化，延缓衰老"]  
      黄芩: ["清热解毒，抗炎抗菌", "凉血止血，收敛伤口", "抗病消炎，增强免疫力", "抗过敏，缓解过敏症状", "保肝解毒，促进肝脏健康", "镇静安神，改善睡眠"]  
      甜叶菊: ["生津止渴，滋润口腔", "降血压，维护心血管健康", "调节血糖，稳定代谢", "提高免疫力", "促进消化，改善食欲", "天然甜味，低热量"]  
      新疆一枝蒿: ["祛风解表，缓解感冒症状", "健胃消积，改善消化功能", "活血解毒，促进血液循环", "抗炎抗菌，增强免疫力", "缓解疼痛，舒缓不适", "促进新陈代谢"]  
      金银花: ["清热解毒，抗炎抗菌", "止痛消炎，缓解肿痛", "抗病毒，增强免疫力", "调节免疫功能", "美容养颜，改善肤质", "促进新陈代谢"]  